[project]
name = "zpp_args"
version = "1.3.3"
description = "Module pour le traitement des arguments d'une ligne de commande"
mainfile = "__init__.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = ["terminal","args","zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/py-zpp_args"
documentation = "https://github.com/ZephyrOff/py-zpp_args"

[project.dependencies]

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["sys", "inspect", "re"]
includes = ["args"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
